// 不動産 建蔽率・容積率 & 敷地面積2Dインタラクティブシミュレータ

export function renderRealEstateSim(container) {
  container.innerHTML = `
    <div class="visualizer-card">
      <div class="visualizer-header">
        <div class="visualizer-badge">第6章 体験ツール</div>
        <h3>🏙️ 建蔽率・容積率 敷地2Dインタラクティブ電卓</h3>
        <p>敷地面積、用途地域、前面道路の幅員を入力して、建築可能な「最大建築面積」と「最大延床面積」をリアルタイム可視化！</p>
      </div>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Input parameters -->
        <div class="calc-panel p-5 bg-card-bg rounded-xl border border-glass">
          <h4 class="font-bold text-md mb-4 text-accent border-b border-glass pb-2">敷地・都市計画条件の設定</h4>

          <div class="form-group mb-4">
            <label class="block text-sm font-semibold mb-1">敷地面積 (㎡)</label>
            <input type="number" id="re-lot-area" class="input-field" value="200" step="10">
          </div>

          <div class="form-group mb-4">
            <label class="block text-sm font-semibold mb-1">指定建蔽率 (%): <span id="re-bcr-val" class="text-accent font-bold">60%</span></label>
            <input type="range" id="re-bcr" min="30" max="80" step="10" value="60" class="range-slider">
          </div>

          <div class="form-group mb-4">
            <label class="block text-sm font-semibold mb-1">指定容積率 (%): <span id="re-far-val" class="text-accent font-bold">200%</span></label>
            <input type="range" id="re-far" min="100" max="500" step="50" value="200" class="range-slider">
          </div>

          <div class="form-group mb-4">
            <label class="block text-sm font-semibold mb-1">前面道路幅員 (m): <span id="re-road-val" class="text-accent font-bold">5.0m</span></label>
            <input type="range" id="re-road" min="2.0" max="15.0" step="0.5" value="5.0" class="range-slider">
          </div>

          <div class="form-group mb-2">
            <label class="block text-sm font-semibold mb-1">用途地域区分 (法定乗数)</label>
            <select id="re-zone-type" class="input-field">
              <option value="0.4" selected>住居系地域 (乗数 0.4)</option>
              <option value="0.6">商業系・工業系地域 (乗数 0.6)</option>
            </select>
          </div>
        </div>

        <!-- Visual output and calculation breakdown -->
        <div class="result-panel p-5 bg-card-bg rounded-xl border border-glass flex flex-col justify-between">
          <div>
            <h4 class="font-bold text-md mb-3 text-accent border-b border-glass pb-2">建築可能面積の計算結果</h4>

            <!-- 2D Canvas Lot diagram -->
            <div class="my-3 p-4 rounded-xl bg-card-bg border border-glass text-center flex flex-col items-center shadow-sm">
              <svg id="re-svg" width="240" height="160" viewBox="0 0 240 160" class="rounded-xl border border-glass bg-surface">
                <!-- SVG elements generated by JS -->
              </svg>
              <div class="text-xs text-muted mt-2" id="re-svg-caption">緑色: 敷地全体 / 青色: 建築面積 (建蔽率)</div>
            </div>

            <div class="space-y-2 text-xs">
              <div class="p-2.5 rounded-lg bg-surface border border-glass flex justify-between items-center">
                <div>
                  <span class="font-bold text-sm block text-foreground">1. 適用建蔽率 (上空からみた投影面積)</span>
                  <span class="text-muted">指定建蔽率と同じ</span>
                </div>
                <span class="text-base font-bold font-mono text-emerald-600 dark:text-emerald-400" id="re-res-bcr">60 % (120 ㎡)</span>
              </div>

              <div class="p-2.5 rounded-lg bg-surface border border-glass flex justify-between items-center">
                <div>
                  <span class="font-bold text-sm block text-foreground">2. 道路幅員による容積率制限</span>
                  <span class="text-muted" id="re-res-road-formula">道路 5m × 0.4 ＝ 200%</span>
                </div>
                <span class="text-base font-bold font-mono text-indigo-700 dark:text-indigo-300" id="re-res-road-limit">200 %</span>
              </div>

              <div class="p-2.5 rounded-lg bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-md flex justify-between items-center">
                <div>
                  <span class="font-bold text-sm text-indigo-100 block">3. 適用容積率 & 最大延床面積</span>
                  <span class="text-indigo-100/90 text-xs" id="re-res-far-applied">Min(200%, 200%) ＝ 200%</span>
                </div>
                <span class="text-lg font-extrabold font-mono text-white" id="re-res-far">200 % (400 ㎡)</span>
              </div>
            </div>
          </div>

          <div class="mt-4 text-xs text-muted bg-surface/40 p-2.5 rounded border border-glass">
            💡 <strong>試験の鉄則:</strong> 前面道路が12m未満の場合、「指定容積率」と「道路幅員×法定乗数(0.4/0.6)」を比較し、<strong>厳しい方（小さい方の数値）</strong>を採用します！
          </div>
        </div>
      </div>
    </div>
  `;

  const lotInput = container.querySelector('#re-lot-area');
  const bcrInput = container.querySelector('#re-bcr');
  const farInput = container.querySelector('#re-far');
  const roadInput = container.querySelector('#re-road');
  const zoneInput = container.querySelector('#re-zone-type');

  const update = () => {
    const lotArea = parseFloat(lotInput.value) || 0;
    const bcr = parseFloat(bcrInput.value) || 60;
    const farSpec = parseFloat(farInput.value) || 200;
    const roadW = parseFloat(roadInput.value) || 5.0;
    const multiplier = parseFloat(zoneInput.value) || 0.4;

    container.querySelector('#re-bcr-val').textContent = bcr + '%';
    container.querySelector('#re-far-val').textContent = farSpec + '%';
    container.querySelector('#re-road-val').textContent = roadW.toFixed(1) + 'm';

    // 1. Building coverage area
    const maxBuildingArea = lotArea * (bcr / 100);

    // 2. Road width limit
    const roadFarLimit = roadW * multiplier * 100; // e.g. 5m * 0.4 = 2.0 = 200%

    // 3. Applied FAR
    const appliedFar = Math.min(farSpec, roadFarLimit);
    const maxFloorArea = lotArea * (appliedFar / 100);

    container.querySelector('#re-res-bcr').textContent = `${bcr}% (${maxBuildingArea.toFixed(1)} ㎡)`;
    container.querySelector('#re-res-road-formula').textContent = `道路 ${roadW.toFixed(1)}m × ${multiplier} ＝ ${roadFarLimit.toFixed(0)}%`;
    container.querySelector('#re-res-road-limit').textContent = roadFarLimit.toFixed(0) + ' %';
    container.querySelector('#re-res-far-applied').textContent = `Min(指定${farSpec}%, 道路制限${roadFarLimit.toFixed(0)}%) ＝ ${appliedFar.toFixed(0)}%`;
    container.querySelector('#re-res-far').textContent = `${appliedFar.toFixed(0)}% (${maxFloorArea.toFixed(1)} ㎡)`;

    // Render SVG
    const svg = container.querySelector('#re-svg');
    const scale = Math.sqrt(bcr / 100);
    const bw = 160 * scale;
    const bh = 100 * scale;
    const bx = (240 - bw) / 2;
    const by = (140 - bh) / 2;

    const isDark = document.documentElement.getAttribute('data-theme') === 'dark';

    svg.innerHTML = `
      <!-- Road -->
      <rect x="0" y="140" width="240" height="20" fill="${isDark ? '#334155' : '#e2e8f0'}" />
      <text x="120" y="153" fill="${isDark ? '#cbd5e1' : '#475569'}" font-size="10" font-weight="bold" text-anchor="middle">前面道路 ${roadW.toFixed(1)}m</text>

      <!-- Lot area -->
      <rect x="40" y="20" width="160" height="100" fill="rgba(16, 185, 129, 0.15)" stroke="#10b981" stroke-width="2" stroke-dasharray="4" />
      <text x="50" y="35" fill="${isDark ? '#34d399' : '#047857'}" font-size="10" font-weight="bold">敷地全体 ${lotArea}㎡</text>

      <!-- Building area -->
      <rect x="${bx}" y="${by}" width="${bw}" height="${bh}" fill="rgba(79, 70, 229, 0.25)" stroke="#6366f1" stroke-width="2" rx="4" />
      <text x="120" y="${by + bh/2 + 4}" fill="${isDark ? '#a5b4fc' : '#3730a3'}" font-size="11" font-weight="bold" text-anchor="middle">
        建築面積 ${maxBuildingArea.toFixed(1)}㎡ (${bcr}%)
      </text>
    `;
  };

  [lotInput, bcrInput, farInput, roadInput, zoneInput].forEach(el => {
    el.addEventListener('input', update);
  });

  update();
}
